spring:
  # 对应 RedisProperties 类
  redis:
    host: 39.108.62.171
    port: 6379
    password: redis123 # Redis 服务器密码，默认为空。生产中，一定要设置 Redis 密码！
    database: 0 # Redis 数据库号，默认为 0 。
    timeout: 0 # Redis 连接超时时间，单位：毫秒。
    # 对应 RedisProperties.Jedis 内部类 ,缺少pool配置会报"NOAUTH Authentication required"
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数，默认为 8 。使用负数表示没有限制。
        max-idle: 8 # 默认连接数最小空闲的连接数，默认为 8 。使用负数表示没有限制。
        min-idle: 0 # 默认连接池最小空闲的连接数，默认为 0 。允许设置 0 和 正数。
        max-wait: -1 # 连接池最大阻塞等待时间，单位：毫秒。默认为 -1 ，表示不限制。
    #集群配置
#    cluster:
#      nodes:
#        - 10.10.202.136:6379
#        - 10.10.202.137:6380
#        - 10.10.202.137:6379
#        - 10.10.202.138:6380
#        - 10.10.202.138:6379
#        - 10.10.202.136:6380
