server:
  port: 8083

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://39.108.62.171:3306/auth-example-20210924?useSSL=false
    username: root
    password: 123456

  # 对应 RedisProperties 类
  redis:
    host: p2wan.fun
    port: 6379
    password: redis123 # Redis 服务器密码，默认为空。生产中，一定要设置 Redis 密码！
    database: 0 # Redis 数据库号，默认为 0 。
    timeout: 0 # Redis 连接超时时间，单位：毫秒。
    # 对应 RedisProperties.Jedis 内部类 ,缺少pool配置会报"NOAUTH Authentication required"
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数，默认为 8 。使用负数表示没有限制。
        max-idle: 8 # 默认连接数最小空闲的连接数，默认为 8 。使用负数表示没有限制。
        min-idle: 0 # 默认连接池最小空闲的连接数，默认为 0 。允许设置 0 和 正数。
        max-wait: -1 # 连接池最大阻塞等待时间，单位：毫秒。默认为 -1 ，表示不限制。

  # RabbitMQ 配置项，对应 RabbitProperties 配置类
  rabbitmq:
    host: 39.108.62.171
    port: 5672
    username: test
    password: test098
    virtual-host: /test
    listener:
      simple:
        acknowledge-mode: manual #自动签收auto（默认），手动manual（建议）
        prefetch: 5 # 限流，单位时间内消费多少条记录
        # 注意！retry只在auto ack模式下才会有效
        retry:
          enabled: true  # 开启重试机制
          max-attempts: 3 # 重试次数
          max-interval: 20000 # 最大间隔时间
          initial-interval: 1000 # 重试间隔时间（单位毫秒）
          multiplier: 2 #乘子  重试间隔*乘子得出下次重试间隔  2s  4s  8s  16s  此处32s>20s  走20s
        default-requeue-rejected: false # 重试次数超过上面的设置之后是否丢弃（false不丢弃时需要写相应代码将该消息加入死信队列）


